{"name": "test_kullanıcı_hatalı_şifreyle_giriş_denediğinde_uyarı_alır", "status": "passed", "description": "D:\\Personal\\_Project\\2025\\universal-test-lab\\tests\\features\\login.feature: Kullanıcı hatalı şifreyle giriş denediğinde uyarı alır", "start": 1752505137287, "stop": 1752505138253, "uuid": "65c685c2-eecc-4164-93d7-31ddb1984374", "historyId": "c930758795c454d04b34815856306ef0", "testCaseId": "c930758795c454d04b34815856306ef0", "fullName": "tests.steps.test_login_steps#test_kullanıcı_hatalı_şifreyle_giriş_denediğinde_uyarı_alır", "labels": [{"name": "parentSuite", "value": "tests.steps"}, {"name": "suite", "value": "test_login_steps"}, {"name": "host", "value": "EVT02136NB"}, {"name": "thread", "value": "25380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.steps.test_login_steps"}]}